SELECT 
CASE WHEN communityName = '' OR communityName= 'nan' THEN NULL ELSE communityName END AS communityName
,CASE WHEN state = '' OR state= 'nan' THEN NULL ELSE state END AS state
,CASE WHEN countyCode = '' OR countyCode= 'nan' THEN NULL ELSE countyCode END AS countyCode
,CASE WHEN communityCode = '' OR communityCode= 'nan' THEN NULL ELSE communityCode END AS communityCode
,CASE WHEN population = '' OR population= 'nan' THEN NULL ELSE population END AS population
,CASE WHEN householdsize = '' OR householdsize= 'nan' THEN NULL ELSE householdsize END AS householdsize
,CASE WHEN racepctblack = '' OR racepctblack= 'nan' THEN NULL ELSE racepctblack END AS racepctblack
,CASE WHEN racePctWhite = '' OR racePctWhite= 'nan' THEN NULL ELSE racePctWhite END AS racePctWhite
,CASE WHEN racePctAsian = '' OR racePctAsian= 'nan' THEN NULL ELSE racePctAsian END AS racePctAsian
,CASE WHEN racePctHisp = '' OR racePctHisp= 'nan' THEN NULL ELSE racePctHisp END AS racePctHisp
,CASE WHEN agePct12t21 = '' OR agePct12t21= 'nan' THEN NULL ELSE agePct12t21 END AS agePct12t21
,CASE WHEN agePct12t29 = '' OR agePct12t29= 'nan' THEN NULL ELSE agePct12t29 END AS agePct12t29
,CASE WHEN agePct16t24 = '' OR agePct16t24= 'nan' THEN NULL ELSE agePct16t24 END AS agePct16t24
,CASE WHEN agePct65up = '' OR agePct65up= 'nan' THEN NULL ELSE agePct65up END AS agePct65up
,CASE WHEN numbUrban = '' OR numbUrban= 'nan' THEN NULL ELSE numbUrban END AS numbUrban
,CASE WHEN pctUrban = '' OR pctUrban= 'nan' THEN NULL ELSE pctUrban END AS pctUrban
,CASE WHEN medIncome = '' OR medIncome= 'nan' THEN NULL ELSE medIncome END AS medIncome
,CASE WHEN pctWWage = '' OR pctWWage= 'nan' THEN NULL ELSE pctWWage END AS pctWWage
,CASE WHEN pctWFarmSelf = '' OR pctWFarmSelf= 'nan' THEN NULL ELSE pctWFarmSelf END AS pctWFarmSelf
,CASE WHEN pctWInvInc = '' OR pctWInvInc= 'nan' THEN NULL ELSE pctWInvInc END AS pctWInvInc
,CASE WHEN pctWSocSec = '' OR pctWSocSec= 'nan' THEN NULL ELSE pctWSocSec END AS pctWSocSec
,CASE WHEN pctWPubAsst = '' OR pctWPubAsst= 'nan' THEN NULL ELSE pctWPubAsst END AS pctWPubAsst
,CASE WHEN pctWRetire = '' OR pctWRetire= 'nan' THEN NULL ELSE pctWRetire END AS pctWRetire
,CASE WHEN medFamInc = '' OR medFamInc= 'nan' THEN NULL ELSE medFamInc END AS medFamInc
,CASE WHEN perCapInc = '' OR perCapInc= 'nan' THEN NULL ELSE perCapInc END AS perCapInc
,CASE WHEN whitePerCap = '' OR whitePerCap= 'nan' THEN NULL ELSE whitePerCap END AS whitePerCap
,CASE WHEN blackPerCap = '' OR blackPerCap= 'nan' THEN NULL ELSE blackPerCap END AS blackPerCap
,CASE WHEN indianPerCap = '' OR indianPerCap= 'nan' THEN NULL ELSE indianPerCap END AS indianPerCap
,CASE WHEN AsianPerCap = '' OR AsianPerCap= 'nan' THEN NULL ELSE AsianPerCap END AS AsianPerCap
,CASE WHEN OtherPerCap = '' OR OtherPerCap= 'nan' THEN NULL ELSE OtherPerCap END AS OtherPerCap
,CASE WHEN HispPerCap = '' OR HispPerCap= 'nan' THEN NULL ELSE HispPerCap END AS HispPerCap
,CASE WHEN NumUnderPov = '' OR NumUnderPov= 'nan' THEN NULL ELSE NumUnderPov END AS NumUnderPov
,CASE WHEN PctPopUnderPov = '' OR PctPopUnderPov= 'nan' THEN NULL ELSE PctPopUnderPov END AS PctPopUnderPov
,CASE WHEN PctLess9thGrade = '' OR PctLess9thGrade= 'nan' THEN NULL ELSE PctLess9thGrade END AS PctLess9thGrade
,CASE WHEN PctNotHSGrad = '' OR PctNotHSGrad= 'nan' THEN NULL ELSE PctNotHSGrad END AS PctNotHSGrad
,CASE WHEN PctBSorMore = '' OR PctBSorMore= 'nan' THEN NULL ELSE PctBSorMore END AS PctBSorMore
,CASE WHEN PctUnemployed = '' OR PctUnemployed= 'nan' THEN NULL ELSE PctUnemployed END AS PctUnemployed
,CASE WHEN PctEmploy = '' OR PctEmploy= 'nan' THEN NULL ELSE PctEmploy END AS PctEmploy
,CASE WHEN PctEmplManu = '' OR PctEmplManu= 'nan' THEN NULL ELSE PctEmplManu END AS PctEmplManu
,CASE WHEN PctEmplProfServ = '' OR PctEmplProfServ= 'nan' THEN NULL ELSE PctEmplProfServ END AS PctEmplProfServ
,CASE WHEN PctOccupManu = '' OR PctOccupManu= 'nan' THEN NULL ELSE PctOccupManu END AS PctOccupManu
,CASE WHEN PctOccupMgmtProf = '' OR PctOccupMgmtProf= 'nan' THEN NULL ELSE PctOccupMgmtProf END AS PctOccupMgmtProf
,CASE WHEN MalePctDivorce = '' OR MalePctDivorce= 'nan' THEN NULL ELSE MalePctDivorce END AS MalePctDivorce
,CASE WHEN MalePctNevMarr = '' OR MalePctNevMarr= 'nan' THEN NULL ELSE MalePctNevMarr END AS MalePctNevMarr
,CASE WHEN FemalePctDiv = '' OR FemalePctDiv= 'nan' THEN NULL ELSE FemalePctDiv END AS FemalePctDiv
,CASE WHEN TotalPctDiv = '' OR TotalPctDiv= 'nan' THEN NULL ELSE TotalPctDiv END AS TotalPctDiv
,CASE WHEN PersPerFam = '' OR PersPerFam= 'nan' THEN NULL ELSE PersPerFam END AS PersPerFam
,CASE WHEN PctFam2Par = '' OR PctFam2Par= 'nan' THEN NULL ELSE PctFam2Par END AS PctFam2Par
,CASE WHEN PctKids2Par = '' OR PctKids2Par= 'nan' THEN NULL ELSE PctKids2Par END AS PctKids2Par
,CASE WHEN PctYoungKids2Par = '' OR PctYoungKids2Par= 'nan' THEN NULL ELSE PctYoungKids2Par END AS PctYoungKids2Par
,CASE WHEN PctTeen2Par = '' OR PctTeen2Par= 'nan' THEN NULL ELSE PctTeen2Par END AS PctTeen2Par
,CASE WHEN PctWorkMomYoungKids = '' OR PctWorkMomYoungKids= 'nan' THEN NULL ELSE PctWorkMomYoungKids END AS PctWorkMomYoungKids
,CASE WHEN PctWorkMom = '' OR PctWorkMom= 'nan' THEN NULL ELSE PctWorkMom END AS PctWorkMom
,CASE WHEN NumKidsBornNeverMar = '' OR NumKidsBornNeverMar= 'nan' THEN NULL ELSE NumKidsBornNeverMar END AS NumKidsBornNeverMar
,CASE WHEN PctKidsBornNeverMar = '' OR PctKidsBornNeverMar= 'nan' THEN NULL ELSE PctKidsBornNeverMar END AS PctKidsBornNeverMar
,CASE WHEN NumImmig = '' OR NumImmig= 'nan' THEN NULL ELSE NumImmig END AS NumImmig
,CASE WHEN PctImmigRecent = '' OR PctImmigRecent= 'nan' THEN NULL ELSE PctImmigRecent END AS PctImmigRecent
,CASE WHEN PctImmigRec5 = '' OR PctImmigRec5= 'nan' THEN NULL ELSE PctImmigRec5 END AS PctImmigRec5
,CASE WHEN PctImmigRec8 = '' OR PctImmigRec8= 'nan' THEN NULL ELSE PctImmigRec8 END AS PctImmigRec8
,CASE WHEN PctImmigRec10 = '' OR PctImmigRec10= 'nan' THEN NULL ELSE PctImmigRec10 END AS PctImmigRec10
,CASE WHEN PctRecentImmig = '' OR PctRecentImmig= 'nan' THEN NULL ELSE PctRecentImmig END AS PctRecentImmig
,CASE WHEN PctRecImmig5 = '' OR PctRecImmig5= 'nan' THEN NULL ELSE PctRecImmig5 END AS PctRecImmig5
,CASE WHEN PctRecImmig8 = '' OR PctRecImmig8= 'nan' THEN NULL ELSE PctRecImmig8 END AS PctRecImmig8
,CASE WHEN PctRecImmig10 = '' OR PctRecImmig10= 'nan' THEN NULL ELSE PctRecImmig10 END AS PctRecImmig10
,CASE WHEN PctSpeakEnglOnly = '' OR PctSpeakEnglOnly= 'nan' THEN NULL ELSE PctSpeakEnglOnly END AS PctSpeakEnglOnly
,CASE WHEN PctNotSpeakEnglWell = '' OR PctNotSpeakEnglWell= 'nan' THEN NULL ELSE PctNotSpeakEnglWell END AS PctNotSpeakEnglWell
,CASE WHEN PctLargHouseFam = '' OR PctLargHouseFam= 'nan' THEN NULL ELSE PctLargHouseFam END AS PctLargHouseFam
,CASE WHEN PctLargHouseOccup = '' OR PctLargHouseOccup= 'nan' THEN NULL ELSE PctLargHouseOccup END AS PctLargHouseOccup
,CASE WHEN PersPerOccupHous = '' OR PersPerOccupHous= 'nan' THEN NULL ELSE PersPerOccupHous END AS PersPerOccupHous
,CASE WHEN PersPerOwnOccHous = '' OR PersPerOwnOccHous= 'nan' THEN NULL ELSE PersPerOwnOccHous END AS PersPerOwnOccHous
,CASE WHEN PersPerRentOccHous = '' OR PersPerRentOccHous= 'nan' THEN NULL ELSE PersPerRentOccHous END AS PersPerRentOccHous
,CASE WHEN PctPersOwnOccup = '' OR PctPersOwnOccup= 'nan' THEN NULL ELSE PctPersOwnOccup END AS PctPersOwnOccup
,CASE WHEN PctPersDenseHous = '' OR PctPersDenseHous= 'nan' THEN NULL ELSE PctPersDenseHous END AS PctPersDenseHous
,CASE WHEN PctHousLess3BR = '' OR PctHousLess3BR= 'nan' THEN NULL ELSE PctHousLess3BR END AS PctHousLess3BR
,CASE WHEN MedNumBR = '' OR MedNumBR= 'nan' THEN NULL ELSE MedNumBR END AS MedNumBR
,CASE WHEN HousVacant = '' OR HousVacant= 'nan' THEN NULL ELSE HousVacant END AS HousVacant
,CASE WHEN PctHousOccup = '' OR PctHousOccup= 'nan' THEN NULL ELSE PctHousOccup END AS PctHousOccup
,CASE WHEN PctHousOwnOcc = '' OR PctHousOwnOcc= 'nan' THEN NULL ELSE PctHousOwnOcc END AS PctHousOwnOcc
,CASE WHEN PctVacantBoarded = '' OR PctVacantBoarded= 'nan' THEN NULL ELSE PctVacantBoarded END AS PctVacantBoarded
,CASE WHEN PctVacMore6Mos = '' OR PctVacMore6Mos= 'nan' THEN NULL ELSE PctVacMore6Mos END AS PctVacMore6Mos
,CASE WHEN MedYrHousBuilt = '' OR MedYrHousBuilt= 'nan' THEN NULL ELSE MedYrHousBuilt END AS MedYrHousBuilt
,CASE WHEN PctHousNoPhone = '' OR PctHousNoPhone= 'nan' THEN NULL ELSE PctHousNoPhone END AS PctHousNoPhone
,CASE WHEN PctWOFullPlumb = '' OR PctWOFullPlumb= 'nan' THEN NULL ELSE PctWOFullPlumb END AS PctWOFullPlumb
,CASE WHEN OwnOccLowQuart = '' OR OwnOccLowQuart= 'nan' THEN NULL ELSE OwnOccLowQuart END AS OwnOccLowQuart
,CASE WHEN OwnOccMedVal = '' OR OwnOccMedVal= 'nan' THEN NULL ELSE OwnOccMedVal END AS OwnOccMedVal
,CASE WHEN OwnOccHiQuart = '' OR OwnOccHiQuart= 'nan' THEN NULL ELSE OwnOccHiQuart END AS OwnOccHiQuart
,CASE WHEN OwnOccQrange = '' OR OwnOccQrange= 'nan' THEN NULL ELSE OwnOccQrange END AS OwnOccQrange
,CASE WHEN RentLowQ = '' OR RentLowQ= 'nan' THEN NULL ELSE RentLowQ END AS RentLowQ
,CASE WHEN RentMedian = '' OR RentMedian= 'nan' THEN NULL ELSE RentMedian END AS RentMedian
,CASE WHEN RentHighQ = '' OR RentHighQ= 'nan' THEN NULL ELSE RentHighQ END AS RentHighQ
,CASE WHEN RentQrange = '' OR RentQrange= 'nan' THEN NULL ELSE RentQrange END AS RentQrange
,CASE WHEN MedRent = '' OR MedRent= 'nan' THEN NULL ELSE MedRent END AS MedRent
,CASE WHEN MedRentPctHousInc = '' OR MedRentPctHousInc= 'nan' THEN NULL ELSE MedRentPctHousInc END AS MedRentPctHousInc
,CASE WHEN MedOwnCostPctInc = '' OR MedOwnCostPctInc= 'nan' THEN NULL ELSE MedOwnCostPctInc END AS MedOwnCostPctInc
,CASE WHEN MedOwnCostPctIncNoMtg = '' OR MedOwnCostPctIncNoMtg= 'nan' THEN NULL ELSE MedOwnCostPctIncNoMtg END AS MedOwnCostPctIncNoMtg
,CASE WHEN NumInShelters = '' OR NumInShelters= 'nan' THEN NULL ELSE NumInShelters END AS NumInShelters
,CASE WHEN NumStreet = '' OR NumStreet= 'nan' THEN NULL ELSE NumStreet END AS NumStreet
,CASE WHEN PctForeignBorn = '' OR PctForeignBorn= 'nan' THEN NULL ELSE PctForeignBorn END AS PctForeignBorn
,CASE WHEN PctBornSameState = '' OR PctBornSameState= 'nan' THEN NULL ELSE PctBornSameState END AS PctBornSameState
,CASE WHEN PctSameHouse85 = '' OR PctSameHouse85= 'nan' THEN NULL ELSE PctSameHouse85 END AS PctSameHouse85
,CASE WHEN PctSameCity85 = '' OR PctSameCity85= 'nan' THEN NULL ELSE PctSameCity85 END AS PctSameCity85
,CASE WHEN PctSameState85 = '' OR PctSameState85= 'nan' THEN NULL ELSE PctSameState85 END AS PctSameState85
,CASE WHEN LemasSwornFT = '' OR LemasSwornFT= 'nan' THEN NULL ELSE LemasSwornFT END AS LemasSwornFT
,CASE WHEN LemasSwFTPerPop = '' OR LemasSwFTPerPop= 'nan' THEN NULL ELSE LemasSwFTPerPop END AS LemasSwFTPerPop
,CASE WHEN LemasSwFTFieldOps = '' OR LemasSwFTFieldOps= 'nan' THEN NULL ELSE LemasSwFTFieldOps END AS LemasSwFTFieldOps
,CASE WHEN LemasSwFTFieldPerPop = '' OR LemasSwFTFieldPerPop= 'nan' THEN NULL ELSE LemasSwFTFieldPerPop END AS LemasSwFTFieldPerPop
,CASE WHEN LemasTotalReq = '' OR LemasTotalReq= 'nan' THEN NULL ELSE LemasTotalReq END AS LemasTotalReq
,CASE WHEN LemasTotReqPerPop = '' OR LemasTotReqPerPop= 'nan' THEN NULL ELSE LemasTotReqPerPop END AS LemasTotReqPerPop
,CASE WHEN PolicReqPerOffic = '' OR PolicReqPerOffic= 'nan' THEN NULL ELSE PolicReqPerOffic END AS PolicReqPerOffic
,CASE WHEN PolicPerPop = '' OR PolicPerPop= 'nan' THEN NULL ELSE PolicPerPop END AS PolicPerPop
,CASE WHEN RacialMatchCommPol = '' OR RacialMatchCommPol= 'nan' THEN NULL ELSE RacialMatchCommPol END AS RacialMatchCommPol
,CASE WHEN PctPolicWhite = '' OR PctPolicWhite= 'nan' THEN NULL ELSE PctPolicWhite END AS PctPolicWhite
,CASE WHEN PctPolicBlack = '' OR PctPolicBlack= 'nan' THEN NULL ELSE PctPolicBlack END AS PctPolicBlack
,CASE WHEN PctPolicHisp = '' OR PctPolicHisp= 'nan' THEN NULL ELSE PctPolicHisp END AS PctPolicHisp
,CASE WHEN PctPolicAsian = '' OR PctPolicAsian= 'nan' THEN NULL ELSE PctPolicAsian END AS PctPolicAsian
,CASE WHEN PctPolicMinor = '' OR PctPolicMinor= 'nan' THEN NULL ELSE PctPolicMinor END AS PctPolicMinor
,CASE WHEN OfficAssgnDrugUnits = '' OR OfficAssgnDrugUnits= 'nan' THEN NULL ELSE OfficAssgnDrugUnits END AS OfficAssgnDrugUnits
,CASE WHEN NumKindsDrugsSeiz = '' OR NumKindsDrugsSeiz= 'nan' THEN NULL ELSE NumKindsDrugsSeiz END AS NumKindsDrugsSeiz
,CASE WHEN PolicAveOTWorked = '' OR PolicAveOTWorked= 'nan' THEN NULL ELSE PolicAveOTWorked END AS PolicAveOTWorked
,CASE WHEN LandArea = '' OR LandArea= 'nan' THEN NULL ELSE LandArea END AS LandArea
,CASE WHEN PopDens = '' OR PopDens= 'nan' THEN NULL ELSE PopDens END AS PopDens
,CASE WHEN PctUsePubTrans = '' OR PctUsePubTrans= 'nan' THEN NULL ELSE PctUsePubTrans END AS PctUsePubTrans
,CASE WHEN PolicCars = '' OR PolicCars= 'nan' THEN NULL ELSE PolicCars END AS PolicCars
,CASE WHEN PolicOperBudg = '' OR PolicOperBudg= 'nan' THEN NULL ELSE PolicOperBudg END AS PolicOperBudg
,CASE WHEN LemasPctPolicOnPatr = '' OR LemasPctPolicOnPatr= 'nan' THEN NULL ELSE LemasPctPolicOnPatr END AS LemasPctPolicOnPatr
,CASE WHEN LemasGangUnitDeploy = '' OR LemasGangUnitDeploy= 'nan' THEN NULL ELSE LemasGangUnitDeploy END AS LemasGangUnitDeploy
,CASE WHEN LemasPctOfficDrugUn = '' OR LemasPctOfficDrugUn= 'nan' THEN NULL ELSE LemasPctOfficDrugUn END AS LemasPctOfficDrugUn
,CASE WHEN PolicBudgPerPop = '' OR PolicBudgPerPop= 'nan' THEN NULL ELSE PolicBudgPerPop END AS PolicBudgPerPop
,CASE WHEN murders = '' OR murders= 'nan' THEN NULL ELSE murders END AS murders
,CASE WHEN murdPerPop = '' OR murdPerPop= 'nan' THEN NULL ELSE murdPerPop END AS murdPerPop
,CASE WHEN rapes = '' OR rapes= 'nan' THEN NULL ELSE rapes END AS rapes
,CASE WHEN rapesPerPop = '' OR rapesPerPop= 'nan' THEN NULL ELSE rapesPerPop END AS rapesPerPop
,CASE WHEN robberies = '' OR robberies= 'nan' THEN NULL ELSE robberies END AS robberies
,CASE WHEN robbbPerPop = '' OR robbbPerPop= 'nan' THEN NULL ELSE robbbPerPop END AS robbbPerPop
,CASE WHEN assaults = '' OR assaults= 'nan' THEN NULL ELSE assaults END AS assaults
,CASE WHEN assaultPerPop = '' OR assaultPerPop= 'nan' THEN NULL ELSE assaultPerPop END AS assaultPerPop
,CASE WHEN burglaries = '' OR burglaries= 'nan' THEN NULL ELSE burglaries END AS burglaries
,CASE WHEN burglPerPop = '' OR burglPerPop= 'nan' THEN NULL ELSE burglPerPop END AS burglPerPop
,CASE WHEN larcenies = '' OR larcenies= 'nan' THEN NULL ELSE larcenies END AS larcenies
,CASE WHEN larcPerPop = '' OR larcPerPop= 'nan' THEN NULL ELSE larcPerPop END AS larcPerPop
,CASE WHEN autoTheft = '' OR autoTheft= 'nan' THEN NULL ELSE autoTheft END AS autoTheft
,CASE WHEN autoTheftPerPop = '' OR autoTheftPerPop= 'nan' THEN NULL ELSE autoTheftPerPop END AS autoTheftPerPop
,CASE WHEN arsons = '' OR arsons= 'nan' THEN NULL ELSE arsons END AS arsons
,CASE WHEN arsonsPerPop = '' OR arsonsPerPop= 'nan' THEN NULL ELSE arsonsPerPop END AS arsonsPerPop
,CASE WHEN ViolentCrimesPerPop = '' OR ViolentCrimesPerPop= 'nan' THEN NULL ELSE ViolentCrimesPerPop END AS ViolentCrimesPerPop
,CASE WHEN nonViolPerPop = '' OR nonViolPerPop= 'nan' THEN NULL ELSE nonViolPerPop END AS nonViolPerPop
,CASE WHEN zip = '' OR zip= 'nan' THEN NULL ELSE zip END AS zip
,CASE WHEN type = '' OR type= 'nan' THEN NULL ELSE type END AS type
,CASE WHEN decommissioned = '' OR decommissioned= 'nan' THEN NULL ELSE decommissioned END AS decommissioned
,CASE WHEN primary_city = '' OR primary_city= 'nan' THEN NULL ELSE primary_city END AS primary_city
,CASE WHEN acceptable_cities = '' OR acceptable_cities= 'nan' THEN NULL ELSE acceptable_cities END AS acceptable_cities
,CASE WHEN unacceptable_cities = '' OR unacceptable_cities= 'nan' THEN NULL ELSE unacceptable_cities END AS unacceptable_cities
,CASE WHEN county = '' OR county= 'nan' THEN NULL ELSE county END AS county
,CASE WHEN timezone = '' OR timezone= 'nan' THEN NULL ELSE timezone END AS timezone
,CASE WHEN area_codes = '' OR area_codes= 'nan' THEN NULL ELSE area_codes END AS area_codes
,CASE WHEN world_region = '' OR world_region= 'nan' THEN NULL ELSE world_region END AS world_region
,CASE WHEN country = '' OR country= 'nan' THEN NULL ELSE country END AS country
,CASE WHEN latitude = '' OR latitude= 'nan' THEN NULL ELSE latitude END AS latitude
,CASE WHEN longitude = '' OR longitude= 'nan' THEN NULL ELSE longitude END AS longitude
,CASE WHEN irs_estimated_population = '' OR irs_estimated_population= 'nan' THEN NULL ELSE irs_estimated_population END AS irs_estimated_population
INTO crime_and_zip_str_null_addressed
FROM crime_and_zip_str
